<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>ModernWorkflows</PackageId>
        <Version>1.0.0</Version>
        <Authors>Lairnan</Authors>
        <Company>Lairnan</Company>
        <Description>Extensions and abstractions for WorkflowCore, including input/output presenters and extended host capabilities.</Description>
        <RepositoryUrl>https://github.com/lairnan/ModernWorkflows</RepositoryUrl>
        <PackageTags>workflowcore;workflows;dotnet8</PackageTags>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DynamicExpresso.Core" Version="2.19.5" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
        <PackageReference Include="WorkflowCore" Version="3.20.0" />
        <PackageReference Include="WorkflowCore.DSL" Version="3.20.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

</Project>