<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DynamicExpresso.Core" Version="2.19.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.5" />
        <PackageReference Include="WorkflowCore" Version="3.13.0" />
        <PackageReference Include="WorkflowCore.DSL" Version="3.13.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Definitions\ShowMessage.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Definitions\WaitInputValue.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
